### ISSUE TITLE
sails-hook-grunt NPM package

### ISSUE THREAD

**Issue by mikermcneil** [boogerlad/sails-hook-grunt#1]
Hey @boogerlad!  We're about ready to pull out the Grunt hook into a standalone hook.  Would you mind if I take over the `sails-hook-grunt` package name on npm?  It'll be less confusing for folks, since it matches the names of our other core standalone hooks (i.e. `sails-hook-orm` and `sails-hook-sockets`).  Thanks!

**Comment by boogerlad** [comment]
Sure! What steps do I need to do to hand over access?

**Comment by mikermcneil** [comment]
@boogerlad sorry for the slow reply, forgot about it until just now when I was about to get started.  Assuming you're logged in to npm, you should be able to do `npm owner add mikermcneil` and it'll just work (I wouldn't suggest doing it in the NPM user interface at the moment-- I've run into some issues w/ that lately)

**Comment by mikermcneil** [comment]
(@boogerlad I should add that you have to do `npm owner add mikermcneil` while `cd`'d inside the package locally)

**Comment by boogerlad** [comment]
done

**Comment by mikermcneil** [comment]
@boogerlad thank you!  I just realized-- is it safe to publish as a patch release?  I don't want to mess up any projects where you're using the existing version (e.g. where you'd have a loose semver range like `sails-hook-grunt@^1.0.2`)

**Comment by boogerlad** [comment]
yes, do as you wish.

**Comment by mikermcneil** [comment]
@boogerlad alright, it's published.  Thank you!  This'll be a dependency of all new Sails projects as of v1
